import previewPositions from "./preview-positions.json";

const asset = (project, file) => `/assets/projects/${project}/${file}.webp`;
const projectPreview = (slug) => `/assets/previews/projects/${slug}.webp`;

function savedPreview(group, slug, defaultPosition) {
  const saved = previewPositions[group]?.[slug];
  const position = typeof saved === "string" ? saved : saved?.position;
  const scale = typeof saved === "object" ? Number(saved.scale) : 1;
  return {
    position: position || defaultPosition,
    scale: Number.isFinite(scale) && scale >= 1 && scale <= 2.5 ? scale : 1,
  };
}

// Edit public text, metadata, routes, and link targets here. Layout lives in main.js.
export const siteContent = {
  global: {
    siteName: "Jianmian Zhang",
    role: "Architectural Designer",
    email: "Jianmian.zhang@mail.polimi.it",
    titleSeparator: " — ",
    itemSeparator: " · ",
    externalArrow: "↗",
    nextArrow: "→",
    downloadArrow: "↓",
    menuLabel: "Menu",
    closeMenuLabel: "Close",
    skipLabel: "Skip to content",
    homeAriaLabel: "Jianmian Zhang home",
    primaryNavigationLabel: "Primary navigation",
    copyrightPrefix: "©",
    navigation: [
      { label: "Projects", href: "/projects" },
      { label: "Competitions", href: "/competitions" },
      { label: "Thesis", href: "/thesis" },
      { label: "About", href: "/about" },
      { label: "Research", href: "/research" },
      { label: "CV", href: "/cv" },
      { label: "Contact", href: "/contact" },
    ],
    footerLinks: [
      { label: "Full Portfolio", href: "/assets/documents/portfolio.pdf", external: true },
      { label: "Email", href: "mailto:Jianmian.zhang@mail.polimi.it" },
    ],
  },
  documents: {
    portfolio: "/assets/documents/portfolio.pdf",
    cv: "/assets/documents/resume.pdf",
    thesis: "/assets/documents/thesis.pdf",
  },
  homepage: {
    title: "Jianmian Zhang — Architectural Designer",
    description:
      "Architectural portfolio of Jianmian Zhang, featuring architecture, adaptive reuse, urban regeneration, building performance, and thesis work.",
    image: "/assets/home/cover.jpg",
    imageAlt: "Jianmian Zhang studio cover with portfolio, competition, thesis, resume, and contact objects",
    frameLabel: "Portfolio landing page",
    hotspots: [
      { id: "portfolio", label: "Open Projects and Portfolio", route: "/projects", left: 38.3, top: 65.8, width: 9.7, height: 24.3 },
      { id: "competition", label: "Open Competitions", route: "/competitions", left: 54.6, top: 57.8, width: 4.2, height: 32.6 },
      { id: "thesis", label: "Open Thesis", route: "/thesis", left: 57.8, top: 63.2, width: 3.6, height: 27.2 },
      { id: "cv", label: "Open CV", route: "/cv", left: 60.6, top: 70.0, width: 3.3, height: 20.8 },
      { id: "contact", label: "Open Contact page", route: "/contact", left: 62.8, top: 58.8, width: 17.6, height: 23.0 },
    ],
  },
  projectsPage: {
    title: "Projects — Jianmian Zhang",
    description: "Selected architecture projects by Jianmian Zhang, presented through their original portfolio pages.",
    eyebrow: "Projects / Portfolio",
    heading: "Selected work",
    viewPortfolioLabel: "View Portfolio",
    downloadLabel: "Download",
    gridLabel: "Six selected projects",
    cardLabelPrefix: "View",
  },
  projectDetail: {
    eyebrowPrefix: "Project",
    metadataLabels: {
      year: "Year",
      location: "Location",
      category: "Type",
      collaboration: "Format",
      role: "Role",
      software: "Software",
      model: "Model",
    },
    portfolioPageLabel: "Portfolio page",
    portfolioPagesLabel: "Original portfolio pages",
    nextLabel: "Next Project",
    nextNavigationLabel: "Next project",
  },
  competitionsPage: {
    title: "Competitions — Jianmian Zhang",
    description: "Verified architecture competition work by Jianmian Zhang, with official sources and original presentation boards.",
    eyebrow: "Competitions",
    heading: "Selected entries",
    gridLabel: "Eight competition entries",
    cardLabelPrefix: "View",
  },
  competitionDetail: {
    eyebrowPrefix: "Competition",
    metadataLabels: {
      organizer: "Organizer",
      result: "Result",
      year: "Year",
      location: "Location",
      published: "Published",
    },
    officialCompetitionLabel: "Official Competition",
    officialResultsLabel: "Official Results",
    boardsLabel: "Complete presentation boards",
    boardAltSuffix: "complete competition board",
    nextLabel: "Next Competition",
    nextNavigationLabel: "Next competition",
  },
  about: {
    title: "About — Jianmian Zhang",
    description: "About Jianmian Zhang, an architectural designer trained in Shenzhen, Milan, and Aarhus.",
    eyebrow: "About",
    heading: "Architectural design grounded in spatial clarity, reuse, and the existing city.",
    profileLabel: "Profile",
    bio:
      "Jianmian Zhang is an architectural designer with a Bachelor of Architecture from Shenzhen University and a Master of Building Architecture at Politecnico di Milano, expected in December 2026. His academic work moves between civic architecture, educational space, urban regeneration, adaptive reuse, and high-rise design. Professional experience at CEBRA in Aarhus includes competition, residential, renovation, and adaptive-reuse work developed through plans, sections, elevations, facade studies, models, and presentation material. Across studies in China and Italy and practice in Denmark, he has built an approach that connects architectural concepts with material, environmental, and technical considerations. Building-performance simulation and computational analysis extend this work as supporting tools for climate-responsive facade design and early-stage design decisions.",
    experienceLabel: "Experience",
    experience: [
      {
        dates: "Aug 2026 — Dec 2026",
        organization: "CEBRA",
        position: "Architect Intern · Full time",
        place: "Aarhus, Denmark",
        description: "Architectural design development across competition, residential, renovation, and adaptive-reuse work through drawings, models, facade studies, material studies, and presentation material.",
      },
      {
        dates: "Feb 2025 — Jul 2025",
        organization: "CEBRA",
        position: "Architect Intern · Full time",
        place: "Aarhus, Denmark",
        description: "Plans, sections, elevations, facade articulation, louver studies, library renovation, and adaptive reuse of an existing prefabricated factory.",
      },
    ],
    educationLabel: "Education",
    education: [
      { dates: "2023 — Expected Dec 2026", institution: "Politecnico di Milano", degree: "Master of Building Architecture", place: "Milan, Italy" },
      { dates: "2018 — 2023", institution: "Shenzhen University", degree: "Bachelor of Architecture", place: "Shenzhen, China" },
    ],
    skillsLabel: "Selected Skills",
    awardsLabel: "Selected Awards & Competitions",
  },
  research: {
    title: "Research & Computational — Jianmian Zhang",
    description: "Building performance and computational design work supporting Jianmian Zhang’s architectural practice.",
    eyebrow: "Research / Computational",
    heading: "Performance analysis as a supporting layer for architectural design.",
    period: "2025 — Present",
    theme: "Simulation-Based Façade Performance Studies",
    context: "Politecnico di Milano · Thesis-linked development",
    intro:
      "A simulation-based workflow studying single-facade performance under controlled boundary conditions, beginning from a thesis context in Naples. The work examines cooling load, daylight relationships, shading depth, window-to-wall ratio, SHGC, orientation, and cross-climate comparison across Naples, Los Angeles, and Boston.",
    methodsLabel: "Methods",
    methods: [
      { number: "01", title: "Simulation", description: "EnergyPlus-based workflows for environmental performance evaluation and parametric studies." },
      { number: "02", title: "Analysis", description: "Python, pandas, scikit-learn, XGBoost, and SHAP for surrogate modelling and interpretable analysis." },
      { number: "03", title: "Design Support", description: "A prototype interface translating simulation results into a more accessible early-stage facade evaluation workflow." },
    ],
    contextLabel: "Architectural Context",
    note: "The research remains connected to facade design, adaptive reuse, urban regeneration, and the environmental consequences of early architectural decisions.",
  },
  cv: {
    title: "CV — Jianmian Zhang",
    description: "CV and selected qualifications of architectural designer Jianmian Zhang.",
    eyebrow: "Curriculum Vitae",
    heading: "Education, practice, selected recognition, and technical capabilities.",
    viewLabel: "View CV",
    downloadLabel: "Download CV",
    educationLabel: "Education",
    practiceLabel: "Practice",
    openPdfLabel: "Open PDF in a new tab",
    embedTitle: "Jianmian Zhang CV",
    pdfNote: "The public CV is available as a PDF. The academic CV informed the research and computational sections but is not published as a download.",
    education: [
      { dates: "2023 — Expected Dec 2026", title: "Master of Building Architecture", place: "Politecnico di Milano · Milan, Italy" },
      { dates: "2018 — 2023", title: "Bachelor of Architecture", place: "Shenzhen University · Shenzhen, China" },
    ],
    practice: [
      { dates: "Aug 2026 — Dec 2026", title: "Architect Intern", place: "CEBRA · Aarhus, Denmark" },
      { dates: "Feb 2025 — Jul 2025", title: "Architect Intern", place: "CEBRA · Aarhus, Denmark" },
    ],
  },
  contactPage: {
    title: "Contact — Jianmian Zhang",
    description: "Contact architectural designer Jianmian Zhang.",
    eyebrow: "Contact",
    name: "Jianmian Zhang",
    role: "Architectural Designer",
    email: "Jianmian.zhang@mail.polimi.it",
    links: [
      { label: "View Portfolio", href: "/assets/documents/portfolio.pdf" },
      { label: "View CV", href: "/assets/documents/resume.pdf" },
    ],
    linkedin: { label: "LinkedIn", href: "" },
  },
  notFound: {
    title: "Page not found — Jianmian Zhang",
    description: "The requested page could not be found.",
    eyebrow: "404",
    heading: "Page not found.",
    returnLabel: "Return home",
  },
  lightbox: {
    dialogLabel: "Expanded project image",
    closeLabel: "Close expanded image",
    closeText: "Close ×",
  },
};

export const thesis = {
  title: "Between the City and the Mostra",
  subtitle: "A New Civic Landscape for Naples",
  pageTitle: "Thesis — Jianmian Zhang",
  description: "Complete thesis by Jianmian Zhang with chapter navigation through the original pages.",
  eyebrow: "Thesis",
  pdf: "/assets/documents/thesis.pdf",
  pageImageTemplate: "/assets/thesis-pages/page-{page}.jpg",
  pageCount: 254,
  pageAltPrefix: "Thesis original page",
  pagesLabel: "Complete thesis pages",
  navigatorLabel: "Chapter Navigator",
  mobileButtonLabel: "Chapters",
  openPdfLabel: "Open original PDF",
  chapters: [
    { id: "part-a-background", level: "part", part: "Part A", title: "Background", startPage: 6 },
    { id: "naples-development", level: "subsection", part: "Part A", number: "1", title: "Naples Development", sourcePage: 12, startPage: 7 },
    { id: "via-terracina-and-mostra-doltremare", level: "subsection", part: "Part A", number: "2", title: "Via Terracina and Mostra d'Oltremare", sourcePage: 24, startPage: 13 },
    { id: "part-b-masterplan-design", level: "part", part: "Part B", title: "MasterPlan Design", startPage: 19 },
    { id: "existing-conditions-analysis", level: "subsection", part: "Part B", number: "1", title: "Existing Conditions Analysis", sourcePage: 38, startPage: 20 },
    { id: "part-b-strategy", level: "subsection", part: "Part B", number: "2", title: "Strategy", sourcePage: 54, startPage: 28 },
    { id: "part-b-function", level: "subsection", part: "Part B", number: "3", title: "Function", sourcePage: 80, startPage: 41 },
    { id: "part-b-morpheme", level: "subsection", part: "Part B", number: "4", title: "Morpheme", sourcePage: 82, startPage: 42 },
    { id: "part-b-tipological-plans", level: "subsection", part: "Part B", number: "5", title: "Tipological plans", sourcePage: 84, startPage: 43 },
    { id: "part-c-preservation-project", level: "part", part: "Part C", title: "Preservation Project", startPage: 48 },
    { id: "background-of-terme-romane", level: "subsection", part: "Part C", number: "1", title: "Background of Terme Romane", sourcePage: 96, startPage: 49 },
    { id: "preservation-material-mapping", level: "subsection", part: "Part C", number: "2", title: "Preservation-Material Mapping", sourcePage: 106, startPage: 54 },
    { id: "preservation-decay-mapping", level: "subsection", part: "Part C", number: "3", title: "Preservation-Decay Mapping", sourcePage: 134, startPage: 68 },
    { id: "preservation-conservation", level: "subsection", part: "Part C", number: "4", title: "Preservation-Conservation", sourcePage: 150, startPage: 76 },
    { id: "additional-part-of-terme-romane", level: "subsection", part: "Part C", number: "5", title: "Additional Part of Terme Romane", sourcePage: 162, startPage: 82 },
    { id: "part-d-buildings-design", level: "part", part: "Part D", title: "Buildings Design", startPage: 91 },
    { id: "part-d-concept", level: "subsection", part: "Part D", number: "1", title: "Concept", sourcePage: 182, startPage: 92 },
    { id: "part-d-reference", level: "subsection", part: "Part D", number: "2", title: "Reference", sourcePage: 190, startPage: 96 },
    { id: "part-d-plan-design", level: "subsection", part: "Part D", number: "3", title: "Plan Design", sourcePage: 194, startPage: 98 },
    { id: "part-d-facade-design", level: "subsection", part: "Part D", number: "4", title: "Façade Design", sourcePage: 214, startPage: 108 },
    { id: "part-d-section-design", level: "subsection", part: "Part D", number: "5", title: "Section Design", sourcePage: 222, startPage: 112 },
    { id: "part-d-detail-design", level: "subsection", part: "Part D", number: "6", title: "Detail Design", sourcePage: 240, startPage: 121 },
    { id: "student-activity-center", level: "subsection", part: "Part D", number: "7", title: "Student Activity Center", sourcePage: 244, startPage: 123 },
    { id: "sport-center-design", level: "subsection", part: "Part D", number: "8", title: "Sport Center Design", sourcePage: 256, startPage: 129 },
    { id: "part-e-sustainable-design", level: "part", part: "Part E", title: "Sustainable Design", startPage: 137 },
    { id: "urban-and-territorial-sustainability", level: "subsection", part: "Part E", number: "1", title: "Urban and Territorial Sustainability", sourcePage: 274, startPage: 138 },
    { id: "part-e-building-scale", level: "subsection", part: "Part E", number: "2", title: "Building Scale", sourcePage: 284, startPage: 143 },
    { id: "part-e-detail-scale", level: "subsection", part: "Part E", number: "3", title: "Detail Scale", sourcePage: 290, startPage: 146 },
    { id: "part-e-element-report", level: "subsection", part: "Part E", number: "4", title: "Element Report", sourcePage: 304, startPage: 153 },
    { id: "part-e-u-value", level: "subsection", part: "Part E", number: "5", title: "U-Value", sourcePage: 310, startPage: 156 },
    { id: "fresh-air-ventilation-system", level: "subsection", part: "Part E", number: "6", title: "Fresh Air Ventilation System", sourcePage: 312, startPage: 157 },
    { id: "heating-and-cooling-system", level: "subsection", part: "Part E", number: "7", title: "Heating and Cooling System", sourcePage: 314, startPage: 158 },
    { id: "environmental-performance-simulation", level: "subsection", part: "Part E", number: "8", title: "Environmental Performance Simulation", sourcePage: 316, startPage: 159 },
    { id: "part-f-system-design", level: "part", part: "Part F", title: "System Design", startPage: 163 },
    { id: "general-calculation-data", level: "subsection", part: "Part F", number: "1", title: "General Calculation Data", sourcePage: 326, startPage: 164 },
    { id: "part-f-u-value", level: "subsection", part: "Part F", number: "2", title: "U-Value", sourcePage: 328, startPage: 165 },
    { id: "thermal-peak-load", level: "subsection", part: "Part F", number: "3", title: "Thermal peak load", sourcePage: 330, startPage: 166 },
    { id: "cooling-peak-load", level: "subsection", part: "Part F", number: "4", title: "Cooling Peak Load", sourcePage: 340, startPage: 171 },
    { id: "ventilation-heating-and-cooling-systems", level: "subsection", part: "Part F", number: "5", title: "Ventilation, heating and cooling systems", sourcePage: 346, startPage: 174 },
    { id: "fan-coil-unit-distribution-and-preliminary-sizing", level: "subsection", part: "Part F", number: "6", title: "Fan coil unit distribution and preliminary sizing", sourcePage: 364, startPage: 183 },
    { id: "waste-water-and-water-supply-for-sanitary-areas", level: "subsection", part: "Part F", number: "7", title: "Waste water and water supply for sanitary areas", sourcePage: 388, startPage: 195 },
    { id: "rainwater-pipes", level: "subsection", part: "Part F", number: "8", title: "Rainwater pipes", sourcePage: 398, startPage: 200 },
    { id: "part-g-structure-design", level: "part", part: "Part G", title: "Structure Design", startPage: 205 },
    { id: "project-description", level: "subsection", part: "Part G", number: "1", title: "Project Description", sourcePage: 410, startPage: 206 },
    { id: "design-code-and-materials", level: "subsection", part: "Part G", number: "2", title: "Design Code & Materials", sourcePage: 412, startPage: 207 },
    { id: "structural-load-calculations", level: "subsection", part: "Part G", number: "3", title: "Structural Load Calculations", sourcePage: 414, startPage: 208 },
    { id: "load-case-and-combinations", level: "subsection", part: "Part G", number: "4", title: "Load Case & Combinations", sourcePage: 420, startPage: 211 },
    { id: "structural-analysis", level: "subsection", part: "Part G", number: "5", title: "Structural Analysis", sourcePage: 422, startPage: 212 },
    { id: "truss-design-and-midas-simplified-model", level: "subsection", part: "Part G", number: "6", title: "Truss Design & Midas Simplified Model", sourcePage: 452, startPage: 227 },
    { id: "column-design", level: "subsection", part: "Part G", number: "7", title: "Column Design", sourcePage: 460, startPage: 231 },
    { id: "verification-with-midas-model", level: "subsection", part: "Part G", number: "8", title: "Verification with Midas Model", sourcePage: 476, startPage: 239 },
    { id: "seismic-analysis-with-midas-model", level: "subsection", part: "Part G", number: "9", title: "Seismic Analysis with Midas Model", sourcePage: 480, startPage: 241 },
    { id: "structural-drawings", level: "subsection", part: "Part G", number: "10", title: "Structural Drawings", sourcePage: 486, startPage: 244 },
    { id: "appendix", level: "subsection", part: "Part G", number: "11", title: "Appendix", sourcePage: 504, startPage: 253 },
    { id: "roman-bath-structure", level: "subsection", part: "Part G", number: "12", title: "Roman Bath Structure", sourcePage: 506, startPage: 254, needsReview: true },
  ],
};

// Projects: edit title, subtitle, year, location, previewImage, and pdfPages here.
export const projects = [
  {
    id: "between-city-mostra",
    slug: "between-city-mostra",
    route: "/projects/between-city-mostra",
    type: "project",
    index: "01",
    title: "Between the City and the Mostra",
    subtitle: "A New Civic Landscape for Naples",
    year: "2025–2026",
    location: "Mostra d’Oltremare, Naples, Italy",
    category: "Urban Regeneration / Library Design",
    collaboration: "Individual work",
    role: "Building design",
    software: "Enscape",
    model: "3D print",
    description:
      "A civic regeneration project that reconnects Naples with the fragmented grounds of Mostra d’Oltremare. A library, student housing, activity centre, sports facilities, and conserved Roman Bath remains form a continuous public landscape across changing ground levels and historical traces.",
    pdfPages: [3, 12],
    homeImage: asset("between-city-mostra", "hero"),
    homeAlt: "Aerial masterplan view connecting Mostra d’Oltremare with the surrounding Naples landscape",
    previewImage: projectPreview("between-city-mostra"),
    previewAlt: "Opening portfolio spread crop showing the Naples civic landscape proposal",
    cardLocation: "Naples, Italy",
    previewPosition: "50% 50%",
    gallery: [
      ["masterplan", "Masterplan and massing studies integrating axes, buildings, landscape, and heritage"],
      ["section-terracina", "Sectional perspective connecting Mostra, Via Terracina, and the northern hill"],
      ["section-landscape", "Transverse section connecting the library wings with the surrounding landscape"],
      ["ground-axonometric", "Ground-level axonometric showing the open civic threshold and central void"],
      ["first-floor", "First-floor axonometric, plan, and sections around the central library void"],
      ["envelope-detail", "Exploded envelope detail integrating facade, structure, shading, and reading edge"],
      ["building-systems", "Structural, heating and cooling, and services plans for the library"],
    ].map(([file, alt]) => ({ src: asset("between-city-mostra", file), alt })),
  },
  {
    id: "run-to-your-club",
    slug: "run-to-your-club",
    route: "/projects/run-to-your-club",
    type: "project",
    index: "02",
    title: "Run to Your Club",
    subtitle: "Reinventing the Form of Learning",
    year: "2023",
    location: "Shenzhen, Guangdong, China",
    category: "Educational Architecture / Sports Space",
    collaboration: "Individual undergraduate work",
    software: "V-Ray",
    description:
      "An atypical architecture school that combines studios, sports clubs, public programmes, and informal learning. A continuous runway moves through the building, linking study, exercise, gathering, and roof-garden spaces into a shared campus experience.",
    pdfPages: [13, 21],
    homeImage: asset("run-to-your-club", "hero"),
    homeAlt: "Exploded axonometric of the Run to Your Club architecture school and orange circulation loop",
    previewImage: projectPreview("run-to-your-club"),
    previewAlt: "Opening portfolio spread crop showing the Run to Your Club architecture school",
    cardLocation: "Shenzhen, China",
    previewPosition: "50% 50%",
    gallery: [
      ["precedent-study", "Yale Art and Architecture Building precedent study and programme analysis"],
      ["spatial-typology", "Diagram combining architecture education and sports clubs into a new spatial type"],
      ["site-evolution", "Campus site strategy and building form evolution studies"],
      ["ground-level", "Public atrium and elevated exhibition hall beneath the architecture school"],
      ["runway-section", "Long section showing the runway connecting study, sports, and club spaces"],
      ["club-section", "Detailed section through sports clubs, studios, and public circulation"],
      ["models", "Roof-garden render and physical models of the architecture school"],
    ].map(([file, alt]) => ({ src: asset("run-to-your-club", file), alt })),
  },
  {
    id: "milano-twin-towers",
    slug: "milano-twin-towers",
    route: "/projects/milano-twin-towers",
    type: "project",
    index: "03",
    title: "Milano Twin Towers",
    subtitle: "Between Old Railway and New Skyline",
    year: "2024",
    location: "Scalo Farini, Milan, Italy",
    category: "Urban Regeneration / Mixed-Use Towers",
    collaboration: "Group master’s work",
    role: "Section design, spatial design, rendering, and drawing production",
    software: "V-Ray, Revit, Rhino",
    description:
      "A mixed-use proposal for the regeneration of Scalo Farini. Office and residential towers rise from a public podium, introducing a new urban node between the former railway landscape, future green space, and Milan’s wider skyline.",
    pdfPages: [22, 27],
    homeImage: asset("milano-twin-towers", "hero"),
    homeAlt: "Twin tower proposal viewed from the former railway landscape at Scalo Farini",
    previewImage: projectPreview("milano-twin-towers"),
    previewAlt: "Opening portfolio spread crop showing the Milano Twin Towers physical model",
    cardLocation: "Milan, Italy",
    previewPosition: "58% 52%",
    gallery: [
      ["urban-strategy", "Scalo Farini urban analysis, masterplan strategy, and site plan"],
      ["vertical-section", "Perspective section through underground, podium, office, and residential programmes"],
      ["gallery", "Interior public gallery beneath the podium"],
      ["podium-section", "Section through the tower, podium, and underground public spaces"],
      ["structure", "Exploded structural axonometric of concrete cores and steel podium"],
      ["facade-detail", "Tower curtain-wall and facade construction study"],
    ].map(([file, alt]) => ({ src: asset("milano-twin-towers", file), alt })),
  },
  {
    id: "reflected-facade",
    slug: "reflected-facade",
    route: "/projects/reflected-facade",
    type: "project",
    index: "04",
    title: "Reflected Façade",
    subtitle: "Tower C at Shenzhen Super Headquarters Base",
    year: "2021–2022",
    location: "Shenzhen, Guangdong, China",
    category: "High-Rise Design / Façade Study",
    collaboration: "Individual undergraduate work",
    software: "V-Ray",
    model: "Laser-cut acrylic and wood",
    description:
      "A multifunctional high-rise exploring how a tower can respond to Shenzhen’s mountain, bay, central green axis, and city skyline. Reflection, structure, and vertical rhythm turn the facade into both an urban landmark and a changing image of the city.",
    pdfPages: [28, 32],
    homeImage: asset("reflected-facade", "hero"),
    homeAlt: "Street-level black-and-white rendering of the Reflected Façade high-rise in Shenzhen",
    previewImage: projectPreview("reflected-facade"),
    previewAlt: "Opening portfolio spread crop showing the Reflected Façade physical study model",
    cardLocation: "Shenzhen, China",
    previewPosition: "50% 50%",
    gallery: [
      ["concept", "Concept sketches and massing studies oriented to mountain, sea, and skyline views"],
      ["aerial", "Aerial rendering of the connected towers, podium, and central bridge"],
      ["atrium", "Interior view of the top-level club and planted atrium"],
      ["tower-plans", "Headquarters office plans at upper levels of Tower B"],
      ["ground-plan", "Ground-level plan showing the two tower lobbies, mall, and access road"],
    ].map(([file, alt]) => ({ src: asset("reflected-facade", file), alt })),
  },
  {
    id: "competition-studies",
    slug: "competition-studies",
    route: "/competitions",
    type: "section-link",
    index: "05",
    title: "Competition Studies",
    subtitle: "Design Training Across Scales",
    year: "2025–2026",
    location: "International competitions",
    category: "Architecture / Adaptive Reuse / Landscape",
    collaboration: "Individual and collaborative work",
    description:
      "A series of short-format competition projects used to train rapid brief analysis, concept development, drawing production, rendering, and visual communication. Selected results include a Top 7 mention and multiple Top 30 finalist placements.",
    pdfPages: [33, 33],
    homeImage: asset("competition-studies", "hero"),
    homeAlt: "Grid of twelve selected architecture competition projects",
    previewImage: projectPreview("competition-studies"),
    previewAlt: "Opening portfolio spread crop showing selected competition renderings",
    cardLocation: "International",
    previewPosition: "50% 50%",
    gallery: [
      ["selected-01", "Oceanic Parliament, Candelo Urban Link, and Abandoned Airport competition entries"],
      ["selected-02", "Rising from Ashes, Florence Hills, and Karlovo Living Landscape competition entries"],
      ["selected-03", "The Sport District, Bodegas Vinival, and La Madreselva competition entries"],
    ].map(([file, alt]) => ({ src: asset("competition-studies", file), alt })),
  },
  {
    id: "fieldwork-and-making",
    slug: "fieldwork-and-making",
    route: "/projects/fieldwork-and-making",
    type: "project",
    index: "06",
    title: "Fieldwork & Making",
    subtitle: "Surveying, Photography, Models, and Art",
    year: "2020–2022",
    location: "Shenzhen, Shanghai, Shantou, and Hangzhou, China",
    category: "Architectural Fieldwork / Representation",
    collaboration: "Individual undergraduate work",
    description:
      "A collection of work beyond the design studio, including measured drawings of a traditional family house, architectural photography, physical model making, and mixed-media art. Together, the studies examine architecture through observation, recording, and construction.",
    pdfPages: [34, 38],
    homeImage: asset("fieldwork-and-making", "hero"),
    homeAlt: "Black-background photograph of a handmade high-rise architectural model",
    previewImage: projectPreview("fieldwork-and-making"),
    previewAlt: "Opening portfolio spread crop showing fieldwork and drawing studies",
    cardLocation: "Multiple cities, China",
    previewPosition: "50% 50%",
    gallery: [
      ["survey-drawings", "Measured drawings and transformation study of a family house in Shantou"],
      ["survey-photography", "Photographic record of traditional residential construction in Shantou"],
      ["architectural-photography", "Selected architectural and urban photography"],
      ["model-process", "Laser cutting, assembly, polishing, and photography process for a physical model"],
      ["artwork", "Mixed-media artwork Talk, completed in March 2020"],
    ].map(([file, alt]) => ({ src: asset("fieldwork-and-making", file), alt })),
  },
];

projects.forEach((project) => {
  const defaultPosition = project.previewPosition || "50% 50%";
  const saved = savedPreview("projects", project.slug, defaultPosition);
  project.previewPosition = saved.position;
  project.previewScale = saved.scale;
  project.previewHoverScale = Math.min(2.5, saved.scale + 0.04);
  if (import.meta.env.DEV) {
    project.previewDefaultPosition = defaultPosition;
    project.previewDefaultScale = 1;
  }
});

export const awards = [
  { result: "Mention · Top 7", title: "Oceanic Parliament", context: "Young Architects Competitions · Collaboration", year: "2026" },
  { result: "Finalist · Top 30", title: "Florence Hills", context: "Terraviva Competition · Collaboration", year: "2025" },
  { result: "Finalist · Top 30", title: "The Field Station", context: "Terraviva Competition · Individual", year: "2025" },
];

export const skills = [
  { title: "Design / BIM", items: ["Revit", "Rhino", "Grasshopper", "AutoCAD"] },
  { title: "Visualization", items: ["Enscape", "V-Ray", "Photoshop", "Illustrator", "InDesign"] },
  { title: "Performance / Computational", items: ["EnergyPlus-based workflows", "Python", "Parametric analysis", "Data-driven analysis"] },
];

const competitionAsset = (file) => `/assets/competitions/${file}.jpg`;
const competitionPreview = (slug) => `/assets/previews/competitions/${slug}.webp`;

// Competitions: edit competition, project, result, dates, links, previewImage, and boards here.
export const competitions = [
  {
    id: "oceanic-parliament",
    slug: "oceanic-parliament",
    route: "/competitions/oceanic-parliament",
    subtitle: "",
    competition: "Oceanic Parliament",
    project: "Oasis on the Garbage Island",
    organizer: "Young Architects Competitions (YAC)",
    result: "Mention · Top 7",
    year: "2026",
    location: "Garbage Patch State · Pacific Ocean",
    resultDate: "2 March 2026",
    officialUrl: "https://www.youngarchitectscompetitions.com/open-competitions/oceanic-parliament",
    resultsUrl: "https://www.youngarchitectscompetitions.com/past-competitions/oceanic-parliament",
    brief:
      "YAC invited designers to imagine an oceanic parliament for the Garbage Patch State: a civic institution set within a territory formed by marine waste. The proposal transforms collected debris into a floating public platform, organizing parliamentary, exhibition and communal spaces around a planted oasis conceived as a symbol of environmental repair.",
    previewImage: competitionPreview("oceanic-parliament"),
    previewAlt: "Rendering of the Oceanic Parliament floating civic oasis",
    cardLocation: "Pacific Ocean",
    boards: [competitionAsset("oceanic-parliament")],
  },
  {
    id: "florence-hills",
    slug: "florence-hills",
    route: "/competitions/florence-hills",
    subtitle: "",
    competition: "Florence Hills",
    project: "Memory of Tuscany",
    organizer: "Terraviva Competitions",
    result: "Finalist · Top 30",
    year: "2025",
    location: "Barberino Tavarnelle · Florence, Italy",
    resultDate: "17 November 2025",
    officialUrl: "https://www.terravivacompetitions.com/wp-content/uploads/Florence-Hills_ENG.pdf",
    resultsUrl: "https://www.terravivacompetitions.com/florence-hills-competition-results-2025/",
    brief:
      "The competition asked designers to revive Podere Santa Margherita as a contemporary residence while preserving the character of its Tuscan rural fabric. Memory of Tuscany uses the existing loggia and arch as a spatial language, reconnecting the manor, rustico and landscape through framed views, planted courts and reversible timber interventions.",
    previewImage: competitionPreview("florence-hills"),
    previewAlt: "Landscape rendering of the Florence Hills adaptive reuse proposal",
    cardLocation: "Florence, Italy",
    boards: [competitionAsset("florence-hills-01"), competitionAsset("florence-hills-02")],
  },
  {
    id: "field-station",
    slug: "field-station",
    route: "/competitions/field-station",
    subtitle: "",
    competition: "The Field Station",
    project: "Floating Boats above the Wetland",
    organizer: "Terraviva Competitions",
    result: "Finalist · Top 30",
    year: "2025",
    location: "Severn River · Virginia, USA",
    resultDate: "5 November 2025",
    officialUrl: "https://www.terravivacompetitions.com/wp-content/uploads/The-Field-Station_ENG.pdf",
    resultsUrl: "https://www.terravivacompetitions.com/the-field-station-competition-results-2025/",
    brief:
      "A multidisciplinary research campus was proposed for the Shenk Property, a sensitive wetland reserve on Virginia’s Severn River. Floating Boats above the Wetland breaks the programme into adaptable timber volumes raised above the marsh, combining research, education and public spaces with a buoyant strategy designed for changing water levels.",
    previewImage: competitionPreview("field-station"),
    previewAlt: "Rendering of research pavilions floating above a Virginia wetland",
    cardLocation: "Virginia, USA",
    boards: [competitionAsset("field-station-01"), competitionAsset("field-station-02")],
  },
  {
    id: "unesco-ancient-theatre",
    slug: "unesco-ancient-theatre",
    route: "/competitions/unesco-ancient-theatre",
    subtitle: "",
    competition: "Unesco Ancient Theatre",
    project: "The Crowned Ring upon the Summit",
    organizer: "Terraviva Competitions",
    result: "Finalist",
    year: "2025",
    location: "Ohrid, North Macedonia",
    resultDate: "10 November 2025",
    officialUrl: "https://www.terravivacompetitions.com/wp-content/uploads/Unesco-Ancient-Theatre_ENG.pdf",
    resultsUrl: "https://www.terravivacompetitions.com/unesco-ancient-theatre-competition-results-2025/",
    brief:
      "The brief called for a sensitive contemporary layer at Ohrid’s ancient theatre, balancing performance, heritage and year-round public use. The Crowned Ring upon the Summit proposes a unifying circular intervention that clarifies circulation, frames the archaeological setting and strengthens the theatre’s relationship with the surrounding city and landscape.",
    previewImage: competitionPreview("unesco-ancient-theatre"),
    previewAlt: "Aerial rendering of the circular intervention at Ohrid's ancient theatre",
    cardLocation: "Ohrid, North Macedonia",
    boards: [competitionAsset("unesco-ancient-theatre-01"), competitionAsset("unesco-ancient-theatre-02")],
  },
  {
    id: "rising-from-ashes",
    slug: "rising-from-ashes",
    route: "/competitions/rising-from-ashes",
    subtitle: "",
    competition: "Rising from Ashes",
    project: "Reconstruction, Remembrance, Recovery",
    organizer: "Terraviva Competitions",
    result: "Finalist · Top 30",
    year: "2026",
    location: "Altadena · California, USA",
    resultDate: "19 January 2026",
    officialUrl: "https://www.terravivacompetitions.com/wp-content/uploads/Rising-from-Ashes_ENG.pdf",
    resultsUrl: "https://www.terravivacompetitions.com/rising-from-ashes-competition-results-2025",
    brief:
      "Following the Los Angeles wildfires, the competition sought a new church and community landscape for Altadena. Reconstruction, Remembrance, Recovery treats rebuilding as both spatial and collective healing, organizing worship, learning and gathering around a sequence of protected courts and landscape thresholds that acknowledge loss while supporting long-term community life.",
    previewImage: competitionPreview("rising-from-ashes"),
    previewAlt: "Exterior rendering of the Rising from Ashes church and community landscape",
    cardLocation: "Altadena, USA",
    boards: [competitionAsset("rising-from-ashes-01"), competitionAsset("rising-from-ashes-02")],
  },
  {
    id: "candelo-urban-link",
    slug: "candelo-urban-link",
    route: "/competitions/candelo-urban-link",
    subtitle: "",
    competition: "Candelo Urban Link",
    project: "Connections",
    organizer: "Terraviva Competitions",
    result: "Finalist · Top 30",
    year: "2026",
    location: "Candelo · Piedmont, Italy",
    resultDate: "16 March 2026",
    officialUrl: "https://www.terravivacompetitions.com/wp-content/uploads/Candelo-Urban-Link_ENG.pdf",
    resultsUrl: "https://www.terravivacompetitions.com/candelo-urban-link-competition-results-2025/",
    brief:
      "The competition focused on an underused square beside Via San Sebastiano, asking for an accessible link between two levels and a flexible civic identity. Connections turns the required ramp into a social armature, combining low-cost tactical elements, gathering spaces and everyday routes for schoolchildren, families and the wider community.",
    previewImage: competitionPreview("candelo-urban-link"),
    previewAlt: "Aerial rendering of the Candelo public square and accessible urban link",
    cardLocation: "Candelo, Italy",
    boards: [competitionAsset("candelo-urban-link-01"), competitionAsset("candelo-urban-link-02")],
  },
  {
    id: "abandoned-airport",
    slug: "abandoned-airport",
    route: "/competitions/abandoned-airport",
    subtitle: "",
    competition: "Abandoned Airport",
    project: "TENT",
    organizer: "Young Architects Competitions (YAC)",
    result: "Finalist · Top 30",
    year: "2026",
    location: "Djúpavogur, Iceland",
    resultDate: "2 February 2026",
    officialUrl: "https://www.youngarchitectscompetitions.com/open-competitions/abandoned-airport",
    resultsUrl: "https://www.youngarchitectscompetitions.com/past-competitions/abandoned-airport",
    brief:
      "YAC asked for three wildlife observation points along the abandoned Djúpavogsflugvöllur runway in eastern Iceland. TENT adapts one quiet triangular prototype to ground, elevated and water-edge conditions. Lightweight timber structures provide distinct viewing postures while minimizing new paths, foundations and visual disturbance within the coastal habitat.",
    previewImage: competitionPreview("abandoned-airport"),
    previewAlt: "Atmospheric rendering of a wildlife observatory on the abandoned Icelandic runway",
    cardLocation: "Djúpavogur, Iceland",
    boards: [competitionAsset("abandoned-airport")],
  },
  {
    id: "karlovo-living-landscape",
    slug: "karlovo-living-landscape",
    route: "/competitions/karlovo-living-landscape",
    subtitle: "",
    competition: "Karlovo Living Landscape",
    project: "IN and OUT",
    organizer: "Terraviva Competitions",
    result: "Finalist · Top 30",
    year: "2026",
    location: "Banská Bystrica, Slovakia",
    resultDate: "27 April 2026",
    officialUrl: "https://www.terravivacompetitions.com/karlovo-living-landscape-competition-2025/",
    resultsUrl: "https://www.terravivacompetitions.com/karlovo-living-landscape-competition-results-2026/",
    brief:
      "Karlovo Living Landscape asked for a compact residential district on the hillside between Banská Bystrica and the forested slopes of Sásovská dolina. IN and OUT explores stepped housing, shared landscape and pedestrian connections that respond to topography while balancing density, community life, ecological continuity and access to the mountain edge.",
    previewImage: competitionPreview("karlovo-living-landscape"),
    previewAlt: "Rendering of stepped hillside housing in the Karlovo Living Landscape proposal",
    cardLocation: "Banská Bystrica, Slovakia",
    boards: [competitionAsset("karlovo-living-landscape-01"), competitionAsset("karlovo-living-landscape-02")],
  },
];

competitions.forEach((entry) => {
  const defaultPosition = "50% 50%";
  const saved = savedPreview("competitions", entry.slug, defaultPosition);
  entry.previewPosition = saved.position;
  entry.previewScale = saved.scale;
  entry.previewHoverScale = Math.min(2.5, saved.scale + 0.04);
  if (import.meta.env.DEV) {
    entry.previewDefaultPosition = defaultPosition;
    entry.previewDefaultScale = 1;
  }
});
